### PR TITLE
setup.py, testcase, travis and gitignore

### PR DESCRIPTION
**Pull request by boeddeker**
This PR is a suggestion.

It is common to have the setup.py in the root directory of the git.
I moved the setup.py to the root directory.

In the readme is mentioned, how the code can be tested.
I added a testcase for that example and added a travis file, so travis can test the code.

I also added a badge from travis to indicate if the build is successful.
When you plan to merge this, it is recommended, that you create a travis acc and activate travis for this repo. Then you can change the badge link to your travis acc.

### CODE REVIEW

**Comment by ludlows** [comment]
Hi Christoph,

Thanks for your PR.
It is a good start.
Could you elaborate what happened in pathlib when you were using python 3.5?

**Comment by boeddeker** [comment]
I wasn't reading the error message properly (https://travis-ci.org/boeddeker/python-pesq/jobs/559939325) and used the fastest solution (i.e. disable test for py35).
In python 3.6 the built-in open function started to support the pathlib module, so the current test fails with python 3.5 and older.
A fix would be to convert the `Path` to a `str` before calling `soundfile.read`

**Comment by ludlows** [comment]
Hi Christoph,

Thanks for the error information.
I see. the error is caused by Soundfile.
so could you replace it with scipy.io.wavfile.read , the same one in the readme ?


Then I can merge your PR.
Thanks.

**Comment by boeddeker** [comment]
Sure, I replaced the read function. 

Btw. do you plan to use travis to test this repo?
The current badge is pointing to my fork.

**Comment by ludlows** [comment]
Hi Christoph,

Thanks for the efforts.

I don't have the account in travis.org yet.
Let it be if you don't mind.

Bests,

**Comment by boeddeker** [comment]
Hmm. When you do not have travis, it would be better to delete the badge in the README.
The badge shows if my fork is working and not if your repo is working.

Also only PR to my fork are tested from travis, but not PR to your repo.

**Comment by ludlows** [comment]
ok.

Thanks a lot for your explanation.
I removed the link to your account in travis .

**Pull request merged**
